# Generated by Django 6.0.2 on 2026-02-16 19:45

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro",
                    models.TextField(
                        blank=True,
                        help_text="Optional intro text shown above the FAQ items.",
                    ),
                ),
                (
                    "faq_items",
                    wagtail.fields.StreamField(
                        [("faq_item", 2)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "The question.", "max_length": 300},
                            ),
                            1: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "help_text": "The answer (supports bold, links, lists, etc.)."
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("question", 0), ("answer", 1)]],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ Page",
            },
            bases=("wagtailcore.page",),
        ),
    ]
