# Generated by Django 6.0.2 on 2026-02-18 14:21

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faqpage",
            name="faq_items",
            field=wagtail.fields.StreamField(
                [("faq_item", 2)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The question visitors will see (e.g. 'What should I wear to my appointment?').",
                            "max_length": 300,
                        },
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "The answer — you can use bold, links, and bullet points."
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 0), ("answer", 1)]],
                        {},
                    ),
                },
            ),
        ),
    ]
