# Generated by Django 6.0.2 on 2026-02-24 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0002_alter_faqpage_faq_items"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="faqpage",
            name="intro_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional image shown beside the intro text.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
