# Generated by Django 6.0.2 on 2026-02-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Uncheck to unsubscribe this address."
                    ),
                ),
                (
                    "ip_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 of the subscriber's IP for rate limiting.",
                        max_length=64,
                    ),
                ),
            ],
            options={
                "verbose_name": "Newsletter subscriber",
                "verbose_name_plural": "Newsletter subscribers",
                "ordering": ["-subscribed_at"],
            },
        ),
        migrations.CreateModel(
            name="SubscribeRateLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_hash", models.CharField(db_index=True, max_length=64)),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ip_hash", "attempted_at"],
                        name="newsletter__ip_hash_f52f86_idx",
                    )
                ],
            },
        ),
    ]
