# Generated by Django 6.0.2 on 2026-02-25 15:19

import uuid
from django.db import migrations, models


def populate_tokens(apps, schema_editor):
    """Assign a unique UUID token to every existing subscriber."""
    Subscriber = apps.get_model("newsletter", "NewsletterSubscriber")
    for sub in Subscriber.objects.filter(token__isnull=True):
        sub.token = uuid.uuid4()
        sub.save(update_fields=["token"])


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0002_newslettercampaign"),
    ]

    operations = [
        # Step 1: Add token field as nullable (no unique constraint yet)
        migrations.AddField(
            model_name="newslettersubscriber",
            name="token",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Secret token for one-click unsubscribe links.",
                null=True,
            ),
        ),
        # Step 2: Populate existing rows with unique UUIDs
        migrations.RunPython(populate_tokens, migrations.RunPython.noop),
        # Step 3: Make the field non-null and unique
        migrations.AlterField(
            model_name="newslettersubscriber",
            name="token",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Secret token for one-click unsubscribe links.",
                unique=True,
            ),
        ),
    ]
