# Generated by Django 6.0.2 on 2026-02-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0003_newslettersubscriber_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newslettercampaign",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("sending", "Sending"),
                    ("sent", "Sent"),
                    ("partial", "Partially Sent"),
                    ("failed", "Failed"),
                ],
                default="draft",
                max_length=10,
            ),
        ),
    ]
