# Generated by Django 6.0.2 on 2026-03-08 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0004_alter_newslettercampaign_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="newslettercampaign",
            name="sent_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Not used — kept for future audit trail.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
