# Generated by Django 6.0.2 on 2026-06-13 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0005_alter_newslettercampaign_sent_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="newslettercampaign",
            name="queued_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the campaign was enqueued for throttled sending.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="newslettercampaign",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("queued", "Queued"),
                    ("sending", "Sending"),
                    ("sent", "Sent"),
                    ("partial", "Partially Sent"),
                    ("failed", "Failed"),
                ],
                default="draft",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="NewsletterDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped (unsubscribed)"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="newsletter.newslettercampaign",
                    ),
                ),
                (
                    "subscriber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="newsletter.newslettersubscriber",
                    ),
                ),
            ],
            options={
                "verbose_name": "Newsletter delivery",
                "verbose_name_plural": "Newsletter deliveries",
                "indexes": [
                    models.Index(
                        fields=["status", "campaign"],
                        name="newsletter__status_b632eb_idx",
                    ),
                    models.Index(
                        fields=["status", "sent_at"],
                        name="newsletter__status_4b0574_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("campaign", "subscriber"),
                        name="unique_campaign_subscriber",
                    )
                ],
            },
        ),
    ]
