# Generated by Django 6.0.2 on 2026-02-16 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro",
                    models.TextField(
                        blank=True,
                        help_text="Optional intro text above the contact info.",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        help_text="Public contact email address.", max_length=254
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(help_text="Public phone number.", max_length=30),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, help_text="Business address (optional)."
                    ),
                ),
                (
                    "map_embed_url",
                    models.URLField(
                        blank=True,
                        help_text="Google Maps embed URL (optional). Use the 'Embed a map' URL from Google Maps.",
                    ),
                ),
                (
                    "contact_form_enabled",
                    models.BooleanField(
                        default=True, help_text="Show the contact form on the page."
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Page",
            },
            bases=("wagtailcore.page",),
        ),
    ]
