# Generated by Django 6.0.2 on 2026-02-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactpage",
            name="facebook_url",
            field=models.URLField(
                blank=True,
                help_text="Facebook page URL (optional). e.g. https://facebook.com/yourbusiness",
            ),
        ),
        migrations.AddField(
            model_name="contactpage",
            name="instagram_url",
            field=models.URLField(
                blank=True,
                help_text="Instagram profile URL (optional). e.g. https://instagram.com/yourbusiness",
            ),
        ),
    ]
