# Generated by Django 6.0.2 on 2026-02-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_contactpage_facebook_url_contactpage_instagram_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactpage",
            name="map_embed_url",
            field=models.URLField(
                blank=True,
                help_text="Google Maps embed URL (optional). Use the 'Embed a map' URL from Google Maps.",
                max_length=500,
            ),
        ),
    ]
