# Generated by Django 6.0.2 on 2026-02-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0003_alter_contactpage_map_embed_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactSubmissionRateLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_hash", models.CharField(db_index=True, max_length=64)),
                ("window_key", models.BigIntegerField(db_index=True)),
                ("submission_count", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ip_hash", "window_key"),
                        name="uniq_contact_rate_ip_window",
                    ),
                ],
            },
        ),
    ]
