# Generated by Django 6.0.2 on 2026-02-24 21:56

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0005_contactsubmission"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Location name, e.g. 'Victoria — Main Office' or 'Nanaimo'.",
                        max_length=200,
                    ),
                ),
                ("address", models.TextField(help_text="Full street address.")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Short note, e.g. 'Available March–May 2026' or 'By appointment only'.",
                        max_length=300,
                    ),
                ),
                (
                    "map_embed_url",
                    models.URLField(
                        blank=True,
                        help_text="Google Maps embed URL (optional).",
                        max_length=500,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as the primary / home location (shown first).",
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Show this location on the contact page. Uncheck to hide temporarily.",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="contact.contactpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
