# Generated by Django 6.0.2 on 2026-03-07 23:48
# EncryptedCharField stores ciphertext; DB column needs 3× logical max_length.

import clients.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0006_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactsubmission",
            name="email",
            field=clients.fields.EncryptedCharField(
                help_text="Submitter's email (encrypted at rest).", max_length=762
            ),
        ),
        migrations.AlterField(
            model_name="contactsubmission",
            name="message",
            field=clients.fields.EncryptedTextField(
                default="", help_text="Message content (encrypted at rest)."
            ),
        ),
        migrations.AlterField(
            model_name="contactsubmission",
            name="name",
            field=clients.fields.EncryptedCharField(
                help_text="Submitter's name (encrypted at rest).", max_length=600
            ),
        ),
        migrations.AlterField(
            model_name="contactsubmission",
            name="phone",
            field=clients.fields.EncryptedCharField(
                blank=True,
                default="",
                help_text="Submitter's phone (encrypted at rest).",
                max_length=90,
            ),
        ),
    ]
