# Generated by Django 6.0.2 on 2026-03-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0009_contactpage_show_cta_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactpage",
            name="cta_button_text",
            field=models.CharField(
                default="Book an Appointment",
                help_text="Text shown on the CTA button.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="contactpage",
            name="cta_button_url",
            field=models.CharField(
                default="/booking/",
                help_text="URL for the CTA button.",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="contactpage",
            name="cta_heading",
            field=models.CharField(
                default="Ready to get started?",
                help_text="Heading for the bottom CTA section.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="contactpage",
            name="cta_text",
            field=models.TextField(
                blank=True,
                default="Book your appointment online in just a few steps.",
                help_text="Optional supporting text below the CTA heading.",
            ),
        ),
    ]
