# Generated by Django 6.0.2 on 2026-02-16 19:27

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServicesIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro",
                    models.TextField(
                        blank=True,
                        help_text="Optional intro text shown above the services grid.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Services Index Page",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ServicePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "short_summary",
                    models.CharField(
                        help_text="One-line summary shown on the services card (e.g., 'Non-invasive full body screening').",
                        max_length=250,
                    ),
                ),
                (
                    "description",
                    wagtail.fields.RichTextField(
                        help_text="Full description shown on the service detail page."
                    ),
                ),
                (
                    "price_label",
                    models.CharField(
                        help_text="Price displayed on the card (e.g., '$150').",
                        max_length=50,
                    ),
                ),
                (
                    "duration_label",
                    models.CharField(
                        blank=True,
                        help_text="Optional duration (e.g., '60 minutes').",
                        max_length=50,
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Featured services may be highlighted on the homepage.",
                    ),
                ),
                (
                    "service_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional image for this service.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Page",
            },
            bases=("wagtailcore.page",),
        ),
    ]
