# Generated by Django 6.0.2 on 2026-02-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicepage",
            name="cal_booking_url",
            field=models.URLField(
                blank=True,
                help_text="Cal.com event type URL for this service (e.g., https://cal.com/yourname/breast-scan). Create a matching Event Type in Cal.com with the correct duration.",
            ),
        ),
    ]
