# Generated by Django 6.0.2 on 2026-02-17 16:47

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_servicepage_cal_booking_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicesindexpage",
            name="cancellation_policy",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Cancellation/rescheduling policy shown below the services grid. Leave blank to hide.",
            ),
        ),
    ]
