# Generated by Django 6.0.2 on 2026-02-17 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_servicesindexpage_cancellation_policy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicesindexpage",
            name="cancellation_policy",
        ),
    ]
