# Generated by Django 6.0.2 on 2026-02-24 20:17

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_remove_servicesindexpage_cancellation_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicesindexpage",
            name="includes_heading",
            field=models.CharField(
                blank=True,
                default="Every service includes",
                help_text="Heading for the 'what's included' card below the intro.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="servicesindexpage",
            name="includes_items",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Bullet list of what every service includes (use a bulleted list).",
            ),
        ),
        migrations.AddField(
            model_name="servicesindexpage",
            name="includes_note",
            field=models.CharField(
                blank=True,
                default="Reports are typically available within 3–4 weeks.",
                help_text="Small note shown below the included items (e.g., turnaround time).",
                max_length=200,
            ),
        ),
    ]
