# Generated by Django 6.0.2 on 2026-02-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_servicesindexpage_includes_heading_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicepage",
            name="image_caption",
            field=models.CharField(
                blank=True,
                help_text="Optional caption displayed below the service image.",
                max_length=250,
            ),
        ),
    ]
