# Generated by Django 6.0.2 on 2026-02-24 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0006_servicepage_image_caption"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicesindexpage",
            name="intro_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional image displayed in the intro section.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
