# Generated by Django 6.0.2 on 2026-02-25 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0007_servicesindexpage_intro_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicepage",
            name="cal_booking_url",
        ),
    ]
