# Generated by Django 6.0.2 on 2026-03-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0009_servicepage_show_cta_servicepage_show_newsletter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicesindexpage",
            name="show_cta",
            field=models.BooleanField(
                default=True, verbose_name="Show 'Book an Appointment' section"
            ),
        ),
        migrations.AddField(
            model_name="servicesindexpage",
            name="show_newsletter",
            field=models.BooleanField(
                default=True, verbose_name="Show newsletter signup"
            ),
        ),
        migrations.AddField(
            model_name="servicesindexpage",
            name="show_policies",
            field=models.BooleanField(
                default=True, verbose_name="Show cancellation / deposit policies"
            ),
        ),
        migrations.AddField(
            model_name="servicesindexpage",
            name="show_testimonials",
            field=models.BooleanField(
                default=True, verbose_name="Show testimonials section"
            ),
        ),
    ]
