# Generated by Django 6.0.2 on 2026-02-22 21:59

import clients.fields
import django.utils.timezone
import modelsearch.index
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    clients.fields.EncryptedCharField(
                        help_text="Client's full name (encrypted at rest).",
                        max_length=200,
                    ),
                ),
                (
                    "phone",
                    clients.fields.EncryptedCharField(
                        blank=True,
                        default="",
                        help_text="Phone number (encrypted at rest).",
                        max_length=30,
                    ),
                ),
                (
                    "email",
                    clients.fields.EncryptedCharField(
                        blank=True,
                        default="",
                        help_text="Email address (encrypted at rest).",
                        max_length=254,
                    ),
                ),
                (
                    "clinic_location",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Which clinic location this client visits (e.g. 'Nanaimo', 'Victoria Pop-Up').",
                        max_length=200,
                    ),
                ),
                (
                    "previous_visit_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("initial_screening", "Initial Screening"),
                            ("follow_up", "Follow-Up"),
                            ("breast_health", "Breast Health"),
                            ("full_body", "Full Body Scan"),
                            ("pain_inflammation", "Pain / Inflammation"),
                            ("other", "Other"),
                        ],
                        default="",
                        help_text="Reason for the most recent visit.",
                        max_length=50,
                    ),
                ),
                (
                    "notes",
                    clients.fields.EncryptedTextField(
                        blank=True,
                        default="",
                        help_text="Internal notes about this client (encrypted at rest).",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "ordering": ["-created_at"],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
    ]
