# Generated by Django 6.0.2 on 2026-02-23 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="last_appointment_date",
            field=models.DateField(
                blank=True,
                help_text="Date of the client's most recent appointment.",
                null=True,
            ),
        ),
    ]
