# Generated by Django 6.0.2 on 2026-02-24 19:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_client_last_appointment_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_file",
                    models.FileField(
                        help_text="Upload the report PDF (or other file).",
                        upload_to="client_reports/",
                    ),
                ),
                (
                    "report_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date the report was generated / received.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending — not yet sent"),
                            ("sent", "Sent to client"),
                            ("reviewed", "Report review completed"),
                        ],
                        default="pending",
                        help_text="Track whether the report has been sent and/or reviewed.",
                        max_length=20,
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="When the report delivery email was sent.",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Internal notes about this report.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        help_text="The client this report belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Report",
                "verbose_name_plural": "Client Reports",
                "ordering": ["-report_date", "-created_at"],
            },
        ),
    ]
