# Generated by Django 6.0.2 on 2026-02-25 21:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_clientreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientreport",
            name="report_date",
            field=models.DateField(
                default=django.utils.timezone.localdate,
                help_text="Date the report was generated / received.",
            ),
        ),
    ]
