# Generated by Django 6.0.2 on 2026-02-25 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_fix_report_date_timezone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientreport",
            name="report_file",
        ),
    ]
