# Generated by Django 6.0.2 on 2026-03-08 01:33

import clients.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0005_remove_clientreport_report_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientreport",
            name="notes",
            field=clients.fields.EncryptedTextField(
                blank=True,
                default="",
                help_text="Internal notes about this report (encrypted at rest).",
            ),
        ),
    ]
