# Generated by Django 6.0.2 on 2026-03-15 13:42

import clients.fields
import django.db.models.deletion
import django.utils.timezone
import modelsearch.index
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0007_encrypt_existing_report_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deposit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("25.00"),
                        help_text="Deposit amount ($).",
                        max_digits=6,
                    ),
                ),
                (
                    "appointment_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of the booked appointment this deposit is for.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending — awaiting payment"),
                            ("received", "Received"),
                            ("forfeited", "Forfeited — client cancelled / no-show"),
                            ("applied", "Applied to service fee"),
                            ("refunded", "Refunded (exception)"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("etransfer", "e-Transfer"),
                            ("cash", "Cash"),
                            ("cheque", "Cheque"),
                        ],
                        default="",
                        help_text="How the client paid (fill in when deposit is received).",
                        max_length=20,
                    ),
                ),
                (
                    "received_date",
                    models.DateField(
                        blank=True,
                        help_text="Date the deposit payment was actually received.",
                        null=True,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e-Transfer confirmation number, cheque number, or other reference.",
                        max_length=200,
                    ),
                ),
                (
                    "notes",
                    clients.fields.EncryptedTextField(
                        blank=True,
                        default="",
                        help_text="Internal notes (encrypted at rest).",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        help_text="The client this deposit belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deposits",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Deposit",
                "verbose_name_plural": "Deposits",
                "ordering": ["-created_at"],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
    ]
