# Generated by Django 6.0.2 on 2026-03-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0008_deposit"),
    ]

    operations = [
        migrations.AddField(
            model_name="deposit",
            name="cal_booking_uid",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Cal.com booking UID (auto-filled by webhook). Used to link cancellations.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="deposit",
            name="deposit_confirmed_sent",
            field=models.BooleanField(
                default=False,
                help_text="Whether the deposit confirmation email has been sent.",
            ),
        ),
        migrations.AddField(
            model_name="deposit",
            name="deposit_request_sent",
            field=models.BooleanField(
                default=False,
                help_text="Whether the deposit request email has been sent to the client.",
            ),
        ),
        migrations.AddField(
            model_name="deposit",
            name="service_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Service booked (auto-filled from Cal.com webhook).",
                max_length=200,
            ),
        ),
    ]
