# Generated by Django 6.0.2 on 2026-03-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0009_deposit_cal_booking_uid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deposit",
            name="status",
            field=models.CharField(
                choices=[
                    ("awaiting_review", "Awaiting Review — owner must approve"),
                    ("pending", "Pending — deposit request sent, awaiting payment"),
                    ("received", "Received"),
                    ("forfeited", "Forfeited — client cancelled / no-show"),
                    ("applied", "Applied to service fee"),
                    ("refunded", "Refunded (exception)"),
                ],
                default="awaiting_review",
                max_length=20,
            ),
        ),
    ]
