# Generated by Django 6.0.2 on 2026-03-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0010_alter_deposit_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="deposit",
            name="approved_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="When the owner approved the booking and sent the deposit request. The 48-hour clock starts here.",
                null=True,
            ),
        ),
    ]
