# Generated by Django 6.0.2 on 2026-03-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0011_deposit_approved_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="email_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                editable=False,
                help_text="SHA-256 hash of lowercased email for O(1) lookups.",
                max_length=64,
            ),
        ),
    ]
