# Generated by Django 6.0.2 on 2026-07-20 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0017_add_expiry_warning_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="deposit",
            name="email_send_error",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                help_text="Reason the last deposit email failed (for troubleshooting).",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="deposit",
            name="email_send_failed",
            field=models.BooleanField(
                default=False,
                help_text="Set automatically if the deposit request email failed to send (e.g. Brevo daily cap reached or API error). Use the Resend button in the Deposits list to try again.",
            ),
        ),
        migrations.AlterField(
            model_name="deposit",
            name="approved_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="When the owner approved the booking and sent the deposit request. The 72-hour clock starts here.",
                null=True,
            ),
        ),
    ]
