# Generated by Django 6.0.2 on 2026-02-16 19:55

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "headline",
                    models.CharField(
                        default="Book an Appointment",
                        help_text="Main heading on the booking page.",
                        max_length=200,
                    ),
                ),
                (
                    "instructions",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Optional instructions shown above the booking widget (e.g., 'Select a service and pick a time').",
                    ),
                ),
                (
                    "booking_embed_url",
                    models.URLField(
                        blank=True,
                        help_text="Embed URL for an iframe booking widget (e.g., Calendly embed link). Leave blank if using a direct link instead.",
                    ),
                ),
                (
                    "booking_link_url",
                    models.URLField(
                        blank=True,
                        help_text="Direct link to the external booking site. Used if no embed URL is provided.",
                    ),
                ),
                (
                    "booking_link_text",
                    models.CharField(
                        default="Book Online",
                        help_text="Text on the booking button (only used with the direct link).",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking Page",
            },
            bases=("wagtailcore.page",),
        ),
    ]
