# Generated by Django 6.0.2 on 2026-02-17 16:47

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingpage",
            name="cancellation_policy",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Cancellation/rescheduling policy shown at the bottom of the booking page. Leave blank to hide.",
            ),
        ),
        migrations.AlterField(
            model_name="bookingpage",
            name="booking_embed_url",
            field=models.URLField(
                blank=True,
                help_text="Optional: Embed URL for a general Cal.com booking widget. Shown below the service selector.",
            ),
        ),
        migrations.AlterField(
            model_name="bookingpage",
            name="booking_link_url",
            field=models.URLField(
                blank=True,
                help_text="Optional: Direct link to the external booking site. Used if no embed URL is provided.",
            ),
        ),
        migrations.AlterField(
            model_name="bookingpage",
            name="instructions",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Optional instructions shown above the service selector (e.g., 'Select a service and pick a time').",
            ),
        ),
    ]
