# Generated by Django 6.0.2 on 2026-02-17 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_bookingpage_cancellation_policy_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookingpage",
            name="cancellation_policy",
        ),
    ]
