# Generated by Django 6.0.2 on 2026-02-21 20:01

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_remove_bookingpage_cancellation_policy"),
        ("services", "0004_remove_servicesindexpage_cancellation_policy"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Location name (e.g., 'Main Clinic — Nanaimo' or 'Victoria Pop-Up').",
                        max_length=200,
                    ),
                ),
                ("address", models.TextField(help_text="Full street address.")),
                (
                    "is_permanent",
                    models.BooleanField(
                        default=False,
                        help_text="Check for a permanent clinic with year-round availability. Uncheck for a travelling pop-up clinic with specific dates.",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="First available date (pop-up clinics only). Leave blank for permanent clinics.",
                        null=True,
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Last available date (pop-up clinics only). Leave blank for permanent clinics.",
                        null=True,
                    ),
                ),
                (
                    "map_embed_url",
                    models.URLField(
                        blank=True,
                        help_text="Google Maps embed URL (optional). Use the 'Embed a map' URL from Google Maps.",
                        max_length=500,
                    ),
                ),
                (
                    "featured_on_homepage",
                    models.BooleanField(
                        default=False,
                        help_text="Show this location as an 'Upcoming Pop-Up' banner on the homepage.",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0,
                        help_text="Lower numbers appear first. Permanent clinics should be 0.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
                "ordering": ["sort_order", "start_date", "name"],
            },
        ),
        migrations.AddField(
            model_name="bookingpage",
            name="timezone_label",
            field=models.CharField(
                default="Pacific Time (PT)",
                help_text="Timezone displayed to visitors so they know what time zone slots are in.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="bookingpage",
            name="booking_embed_url",
            field=models.URLField(
                blank=True,
                help_text="Optional: Embed URL for a general Cal.com booking widget (fallback).",
            ),
        ),
        migrations.AlterField(
            model_name="bookingpage",
            name="booking_link_text",
            field=models.CharField(
                default="Book Online",
                help_text="Text on the booking button (only used with the direct link fallback).",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="bookingpage",
            name="booking_link_url",
            field=models.URLField(
                blank=True,
                help_text="Optional: Direct link to the external booking site (fallback).",
            ),
        ),
        migrations.AlterField(
            model_name="bookingpage",
            name="instructions",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Optional instructions shown above the booking flow.",
            ),
        ),
        migrations.CreateModel(
            name="LocationServiceLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "cal_booking_url",
                    models.URLField(
                        help_text="Cal.com event type URL for this service at this location (e.g., https://cal.com/yourname/breast-scan-victoria-mar15)."
                    ),
                ),
                (
                    "location",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_links",
                        to="booking.location",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        help_text="Which service is offered at this location.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_links",
                        to="services.servicepage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service at this location",
                "verbose_name_plural": "Services at this location",
                "ordering": ["sort_order"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("location", "service"), name="uniq_location_service"
                    )
                ],
            },
        ),
    ]
