# Generated by Django 6.0.2 on 2026-02-24 15:37

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0004_location_bookingpage_timezone_label_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvailabilityBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(help_text="First day you'll be at this location."),
                ),
                (
                    "end_date",
                    models.DateField(help_text="Last day you'll be at this location."),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        help_text="Internal notes — not shown to visitors (e.g., 'Morning only').",
                        max_length=200,
                    ),
                ),
                (
                    "featured_on_homepage",
                    models.BooleanField(
                        default=True,
                        help_text="Show this visit on the homepage as an upcoming pop-up.",
                    ),
                ),
                (
                    "location",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_blocks",
                        to="booking.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Availability",
                "verbose_name_plural": "Availability",
                "ordering": ["start_date"],
            },
        ),
    ]
