# Generated by Django 6.0.2 on 2026-02-25 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_availabilityblock"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="locationservicelink",
            name="uniq_location_service",
        ),
        migrations.AlterModelOptions(
            name="location",
            options={
                "ordering": ["sort_order", "name"],
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
            },
        ),
        migrations.RemoveField(
            model_name="location",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="location",
            name="start_date",
        ),
        migrations.AddField(
            model_name="location",
            name="cal_booking_url",
            field=models.URLField(
                blank=True,
                help_text="Cal.com booking URL for this location. For pop-ups, this is a single booking link for the visit (all services, date-restricted in Cal.com). Leave blank for permanent clinics — each service's own Cal URL is used.",
                max_length=500,
            ),
        ),
        migrations.DeleteModel(
            name="LocationServiceLink",
        ),
    ]
