# Generated by Django 6.0.2 on 2026-02-25 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0006_remove_locationservicelink_uniq_location_service_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="cal_booking_url",
        ),
    ]
