# Generated by Django 6.0.2 on 2026-02-25 02:45

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0007_remove_location_cal_booking_url"),
        ("services", "0008_location_service_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck to hide this location from the booking page. Permanent clinics should always be active. Toggle pop-ups on/off as trips are planned.",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="schedule_text",
            field=models.CharField(
                blank=True,
                help_text="Displayed schedule or upcoming dates for visitors. e.g., 'Tuesdays & Thursdays, 9am – 4pm' for home clinic, or 'March 15–17, 2026' for a pop-up visit.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="featured_on_homepage",
            field=models.BooleanField(
                default=False,
                help_text="Show this location on the homepage (e.g., as an upcoming pop-up).",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="is_permanent",
            field=models.BooleanField(
                default=False,
                help_text="Check for a permanent clinic with year-round availability. Uncheck for a travelling pop-up clinic.",
            ),
        ),
        migrations.CreateModel(
            name="LocationServiceLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cal_booking_url",
                    models.URLField(
                        help_text="Cal.com event-type URL for this service at this location (e.g., https://cal.com/you/full-body-nanaimo)."
                    ),
                ),
                (
                    "location",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_links",
                        to="booking.location",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        help_text="The service offered at this location.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_links",
                        to="services.servicepage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service booking link",
                "verbose_name_plural": "Service booking links",
                "ordering": ["service__title"],
                "unique_together": {("location", "service")},
            },
        ),
        migrations.DeleteModel(
            name="AvailabilityBlock",
        ),
    ]
