# Generated by Django 6.0.2 on 2026-02-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0008_location_service_links"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="is_active",
        ),
        migrations.AddField(
            model_name="location",
            name="display_until",
            field=models.DateField(
                blank=True,
                help_text="Pop-up clinics: set the last day of the visit (e.g., March 17). The location auto-shows until this date passes, then auto-hides. Leave blank for permanent clinics (they're always visible).",
                null=True,
            ),
        ),
    ]
