# Generated by Django 6.0.2 on 2026-02-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0009_display_until_replaces_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="starts_on",
            field=models.DateField(
                blank=True,
                help_text="First date with availability (e.g., March 14). The Cal.com calendar opens directly on this date so clients don't have to click through months. Leave blank to default to today.",
                null=True,
            ),
        ),
    ]
