# Generated by Django 6.0.2 on 2026-03-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0010_location_starts_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingpage",
            name="show_newsletter",
            field=models.BooleanField(
                default=True, verbose_name="Show newsletter signup"
            ),
        ),
        migrations.AddField(
            model_name="bookingpage",
            name="show_policies",
            field=models.BooleanField(
                default=True, verbose_name="Show cancellation / deposit policies"
            ),
        ),
        migrations.AddField(
            model_name="bookingpage",
            name="show_testimonials",
            field=models.BooleanField(
                default=True, verbose_name="Show testimonials section"
            ),
        ),
    ]
