# Generated by Django 6.0.2 on 2026-03-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0011_bookingpage_show_newsletter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingpage",
            name="change_location_text",
            field=models.CharField(
                default="← Change location",
                help_text="Button to go back and change the selected location.",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="bookingpage",
            name="first_time_text",
            field=models.CharField(
                blank=True,
                default="First time? Learn what to expect →",
                help_text="Link below the header. Leave blank to hide.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="bookingpage",
            name="loading_calendar_text",
            field=models.CharField(
                default="Loading calendar…",
                help_text="Shown while the booking calendar loads.",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="bookingpage",
            name="no_booking_button_text",
            field=models.CharField(
                default="Contact Us",
                help_text="Button text when booking isn't available.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="bookingpage",
            name="no_booking_message",
            field=models.TextField(
                default="Online booking for this service at this location isn't available yet.\n\nPlease contact us to schedule.",
                help_text="Shown when a service has no Cal.com URL configured. Use line breaks for multiple paragraphs.",
            ),
        ),
        migrations.AddField(
            model_name="bookingpage",
            name="policy_checkbox_error",
            field=models.CharField(
                default="Please agree to the policy before booking.",
                help_text="Error message when checkbox is not checked.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="bookingpage",
            name="policy_checkbox_label",
            field=models.CharField(
                default="I have read and agree to the cancellation and payment policy.",
                help_text="Label for the required policy agreement checkbox.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="bookingpage",
            name="step1_description",
            field=models.CharField(
                blank=True,
                default="Select where you'd like your appointment.",
                help_text="Description under the heading. Leave blank to hide.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="bookingpage",
            name="step1_heading",
            field=models.CharField(
                default="Choose a Location",
                help_text="Heading for step 1.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="bookingpage",
            name="step2_description_prefix",
            field=models.CharField(
                default="Select the service you'd like to book at",
                help_text="Text before the location name, e.g. 'Select the service you'd like to book at'.",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="bookingpage",
            name="step2_heading",
            field=models.CharField(
                default="Choose a Service",
                help_text="Heading for step 2.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="bookingpage",
            name="step2_no_services_message",
            field=models.CharField(
                default="No services are currently available at this location.",
                help_text="Shown when a location has no services configured.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="bookingpage",
            name="step2_try_different_location",
            field=models.CharField(
                default="← Try a different location",
                help_text="Button text when no services are available.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="bookingpage",
            name="step3_change_service_text",
            field=models.CharField(
                default="← Change",
                help_text="Button to go back and change the selected service.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="bookingpage",
            name="step3_heading",
            field=models.CharField(
                default="Pick a Date & Time",
                help_text="Heading for step 3.",
                max_length=100,
            ),
        ),
    ]
