# Generated by Django 6.0.2 on 2026-03-15 18:56

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0012_bookingpage_change_location_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingpage",
            name="deposit_instructions",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="After booking, you will receive an email with payment instructions.",
                help_text="Shown in the policy section on the booking page. Explain how clients should pay their deposit.",
            ),
        ),
    ]
