# Generated by Django 6.0.2 on 2026-10-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0015_placeholderbooking"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="booking_phone",
            field=models.CharField(
                blank=True,
                help_text="Phone number clients call to book. Required for 'Call to book' locations.",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="booking_phone_note",
            field=models.CharField(
                blank=True,
                help_text="Optional note shown with the phone number, e.g. 'Call Monday–Friday, 9am – 4pm to schedule.'",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="booking_type",
            field=models.CharField(
                choices=[
                    (
                        "online",
                        "Online — Cal.com calendar (choose a service, then pick a time)",
                    ),
                    ("call", "Call to book — client phones the clinic to schedule"),
                ],
                default="online",
                help_text="How clients book at this location. 'Online' uses the per-service Cal.com calendars below. 'Call to book' shows a phone number instead and skips the online calendar (no Cal.com links needed).",
                max_length=10,
            ),
        ),
    ]
