# Generated by Django 6.0.2 on 2026-10-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0016_location_booking_phone_location_booking_phone_note_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="booking_website_url",
            field=models.URLField(
                blank=True,
                help_text="Optional website link for this clinic (e.g. the partner clinic's own website or booking page). Shown with the phone number on call-to-book locations.",
                max_length=500,
            ),
        ),
    ]
