# Generated by Django 6.0.2 on 2026-02-16 19:34

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro",
                    models.TextField(
                        blank=True,
                        help_text="Optional intro text shown above the articles.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Index Page",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="BlogPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "publish_date",
                    models.DateField(
                        help_text="The date shown on the article (used for ordering)."
                    ),
                ),
                (
                    "author_name",
                    models.CharField(
                        help_text="Author name displayed on the article.",
                        max_length=100,
                    ),
                ),
                (
                    "excerpt",
                    models.CharField(
                        help_text="Short summary shown on the blog listing card (max 300 chars).",
                        max_length=300,
                    ),
                ),
                (
                    "body",
                    wagtail.fields.RichTextField(help_text="The full article content."),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Featured posts may be highlighted on the homepage.",
                    ),
                ),
                (
                    "cover_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional cover image shown at the top of the post and on the card.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Post",
                "ordering": ["-publish_date"],
            },
            bases=("wagtailcore.page",),
        ),
    ]
