# Generated by Django 6.0.2 on 2026-02-16 19:39

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="external_url",
            field=models.URLField(
                blank=True,
                help_text="Link to an external article. If filled, the card links here instead of a detail page.",
            ),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="The full article content. Leave empty for external links.",
            ),
        ),
    ]
