# Generated by Django 6.0.2 on 2026-02-17 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blogpage_external_url_alter_blogpage_body"),
        ("services", "0003_servicesindexpage_cancellation_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="related_service",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: link this article to a specific service. A booking button will appear at the bottom.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blog_posts",
                to="services.servicepage",
            ),
        ),
    ]
