# Generated by Django 6.0.2 on 2026-02-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_blogpage_related_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="citation",
            field=models.TextField(
                blank=True,
                help_text="Citation or credit for the article source/author (e.g., 'Smith, J. (2025). Thermography Today, 12(3), 45-52.').",
            ),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="source_url",
            field=models.URLField(
                blank=True, help_text="Optional link to the original source article."
            ),
        ),
    ]
