# Generated by Django 6.0.2 on 2026-02-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_blogpage_citation_blogpage_source_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="category",
            field=models.CharField(
                choices=[
                    ("what-is-thermography", "What is Thermography?"),
                    ("articles", "Articles"),
                ],
                default="articles",
                help_text="Which section this post belongs to on the Resources page.",
                max_length=50,
            ),
        ),
    ]
