# Generated by Django 6.0.2 on 2026-02-18 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_blogpage_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpage",
            options={"verbose_name": "Blog Post"},
        ),
    ]
