# Generated by Django 6.0.2 on 2026-02-21 21:19

import django.db.models.deletion
import modelsearch.index
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_blogpage_options"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name (e.g., 'Dr. Jane Smith').", max_length=150
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        choices=[
                            ("thermographer", "Thermographer"),
                            ("hormone-practitioner", "Hormone Practitioner"),
                            ("naturopath", "Naturopath"),
                            ("health-coach", "Health Coach"),
                            ("other", "Other"),
                        ],
                        default="thermographer",
                        help_text="Primary specialty — used for the badge label.",
                        max_length=50,
                    ),
                ),
                (
                    "title_role",
                    models.CharField(
                        blank=True,
                        help_text="Professional title, e.g. 'Certified Clinical Thermographer' or 'RHN, Hormone Health Specialist'.",
                        max_length=200,
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        help_text="Short bio (2–4 sentences). What they do & why they're great."
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        help_text="Link to their website or profile (optional).",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Uncheck to hide without deleting."
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Professional headshot (square crop works best).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expert",
                "verbose_name_plural": "Experts",
                "ordering": ["sort_order", "name"],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
    ]
