# Generated by Django 6.0.2 on 2026-02-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_expert"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expert",
            name="specialty",
            field=models.CharField(
                blank=True,
                help_text="Primary specialty — e.g. 'Thermographer', 'Naturopath', 'Hormone Health Specialist'.",
                max_length=100,
            ),
        ),
    ]
