# Generated by Django 6.0.2 on 2026-03-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_expert_specialty_free_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="show_cta",
            field=models.BooleanField(
                default=True, verbose_name="Show 'Book an Appointment' button"
            ),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="show_newsletter",
            field=models.BooleanField(
                default=True, verbose_name="Show newsletter signup"
            ),
        ),
    ]
