# Generated by Django 6.0.2 on 2026-03-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_blogindexpage_show_cta_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogindexpage",
            name="cta_button_text",
            field=models.CharField(
                default="Book an Appointment",
                help_text="Text shown on the CTA button.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="blogindexpage",
            name="cta_button_url",
            field=models.CharField(
                default="/booking/",
                help_text="URL for the CTA button.",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="blogindexpage",
            name="cta_heading",
            field=models.CharField(
                default="Need personalized guidance?",
                help_text="Heading for the bottom CTA section.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="blogindexpage",
            name="cta_text",
            field=models.TextField(
                blank=True,
                default="Book an appointment to discuss your goals and next steps.",
                help_text="Optional supporting text below the CTA heading.",
            ),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="cta_button_text",
            field=models.CharField(
                default="Book an Appointment",
                help_text="Default CTA button text.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="cta_button_url",
            field=models.CharField(
                default="/booking/",
                help_text="Default CTA URL.",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="cta_text",
            field=models.CharField(
                blank=True,
                default="Interested in learning more?",
                help_text="Short text shown above the button when no related service is selected.",
                max_length=200,
            ),
        ),
    ]
