# Generated by Django 6.0.2 on 2026-02-16 16:16

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero", 5),
                    ("text_section", 6),
                    ("text_with_image", 11),
                    ("testimonial", 15),
                    ("news_item", 20),
                    ("call_to_action", 24),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Main heading (e.g., 'Welcome to Thermography')",
                            "max_length": 200,
                        },
                    ),
                    1: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Text below the heading", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Book an Appointment",
                            "help_text": "Text on the button",
                            "max_length": 50,
                        },
                    ),
                    3: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "default": "/booking/",
                            "help_text": "Where the button links to",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Background image (optional)", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 0),
                                ("subheading", 1),
                                ("button_text", 2),
                                ("button_link", 3),
                                ("background_image", 4),
                            ]
                        ],
                        {},
                    ),
                    6: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "icon": "pilcrow",
                            "label": "Text Section",
                            "template": "home/blocks/richtext_block.html",
                        },
                    ),
                    7: ("wagtail.blocks.CharBlock", (), {"max_length": 200}),
                    8: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Formatted text — supports bold, links, lists, etc."
                        },
                    ),
                    9: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "right",
                            "help_text": "'left' or 'right' — which side the image appears on",
                            "max_length": 5,
                        },
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 7),
                                ("text", 8),
                                ("image", 9),
                                ("image_position", 10),
                            ]
                        ],
                        {},
                    ),
                    12: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "The testimonial text"},
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Client name", "max_length": 100},
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "e.g., 'Client since 2024' (optional)",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 12), ("author", 13), ("role", 14)]],
                        {},
                    ),
                    16: ("wagtail.blocks.DateBlock", (), {}),
                    17: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Short description"},
                    ),
                    18: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Link to full article (optional)",
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "News",
                            "help_text": "'News' or 'Event'",
                            "max_length": 20,
                        },
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 7),
                                ("date", 16),
                                ("summary", 17),
                                ("link", 18),
                                ("category", 19),
                            ]
                        ],
                        {},
                    ),
                    21: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    22: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Book Now", "max_length": 50},
                    ),
                    23: ("wagtail.blocks.URLBlock", (), {"default": "/booking/"}),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 7),
                                ("text", 21),
                                ("button_text", 22),
                                ("button_link", 23),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
