# Generated by Django 6.0.2 on 2026-02-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_sitesettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="business_name",
            field=models.CharField(
                default="Thermography Vancouver Island",
                help_text="Business name shown in the header and footer.",
                max_length=100,
            ),
        ),
    ]
