# Generated by Django 6.0.2 on 2026-02-17 16:50

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_sitesettings_business_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="cancellation_policy",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Cancellation/rescheduling policy shown on the booking and services pages. Leave blank to hide.",
            ),
        ),
    ]
