# Generated by Django 6.0.2 on 2026-02-17 22:33

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_sitesettings_cancellation_policy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("announcement", 3),
                    ("hero", 9),
                    ("text_section", 10),
                    ("three_column_feature", 16),
                    ("text_with_image", 21),
                    ("two_column_info", 27),
                    ("services_grid", 31),
                    ("checklist", 37),
                    ("trust", 43),
                    ("why_choose_us", 47),
                    ("testimonial", 51),
                    ("news_item", 56),
                    ("faq_preview", 59),
                    ("call_to_action", 63),
                    ("big_cta", 66),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Announcement text (supports links, bold, etc.)."
                        },
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("info", "Info — teal/brand"),
                                ("warning", "Warning — amber"),
                                ("success", "Success — green"),
                            ],
                            "help_text": "Colour scheme for the banner.",
                        },
                    ),
                    2: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Allow visitors to dismiss this banner?",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("message", 0), ("style", 1), ("dismissible", 2)]],
                        {},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Main heading (e.g., 'Welcome to Thermography')",
                            "max_length": 200,
                        },
                    ),
                    5: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Text below the heading", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Book an Appointment",
                            "help_text": "Text on the button",
                            "max_length": 50,
                        },
                    ),
                    7: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "default": "/booking/",
                            "help_text": "Where the button links to",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Background image (optional)", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 4),
                                ("subheading", 5),
                                ("button_text", 6),
                                ("button_link", 7),
                                ("background_image", 8),
                            ]
                        ],
                        {},
                    ),
                    10: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "icon": "pilcrow",
                            "label": "Text Section",
                            "template": "home/blocks/richtext_block.html",
                        },
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional heading above the three columns.",
                            "max_length": 200,
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Heroicon name (e.g. 'shield-check', 'heart', 'eye'). Leave blank for a default circle.",
                            "max_length": 30,
                            "required": False,
                        },
                    ),
                    13: ("wagtail.blocks.CharBlock", (), {"max_length": 100}),
                    14: ("wagtail.blocks.TextBlock", (), {}),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("icon_name", 12), ("heading", 13), ("text", 14)]],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("section_heading", 11),
                                ("column_1", 15),
                                ("column_2", 15),
                                ("column_3", 15),
                            ]
                        ],
                        {},
                    ),
                    17: ("wagtail.blocks.CharBlock", (), {"max_length": 200}),
                    18: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Formatted text — supports bold, links, lists, etc."
                        },
                    ),
                    19: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "right",
                            "help_text": "'left' or 'right' — which side the image appears on",
                            "max_length": 5,
                        },
                    ),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 17),
                                ("text", 18),
                                ("image", 19),
                                ("image_position", 20),
                            ]
                        ],
                        {},
                    ),
                    22: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 200, "required": False},
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Heading for the left column.",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    24: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Left column content."},
                    ),
                    25: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Heading for the right column.",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    26: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Right column content."},
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 22),
                                ("left_heading", 23),
                                ("left_content", 24),
                                ("right_heading", 25),
                                ("right_content", 26),
                            ]
                        ],
                        {},
                    ),
                    28: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Our Services", "max_length": 200},
                    ),
                    29: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Optional text below the heading.",
                            "required": False,
                        },
                    ),
                    30: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "If checked, only services marked 'Featured' will display.",
                            "required": False,
                        },
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 28), ("subheading", 29), ("featured_only", 30)]],
                        {},
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "What to Expect", "max_length": 200},
                    ),
                    33: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Optional intro text above the list.",
                            "required": False,
                        },
                    ),
                    34: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Checklist item text.", "max_length": 300},
                    ),
                    35: ("wagtail.blocks.StructBlock", [[("text", 34)]], {}),
                    36: ("wagtail.blocks.ListBlock", (35,), {}),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 32), ("intro", 33), ("items", 36)]],
                        {},
                    ),
                    38: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Trusted & Certified",
                            "max_length": 200,
                            "required": False,
                        },
                    ),
                    39: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Logo or badge image (optional).",
                            "required": False,
                        },
                    ),
                    40: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Label (e.g. 'IACT Certified').",
                            "max_length": 100,
                        },
                    ),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 39), ("label", 40)]],
                        {},
                    ),
                    42: ("wagtail.blocks.ListBlock", (41,), {}),
                    43: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 38), ("items", 42)]],
                        {},
                    ),
                    44: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Why Choose Us?", "max_length": 200},
                    ),
                    45: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 13), ("text", 14)]],
                        {},
                    ),
                    46: ("wagtail.blocks.ListBlock", (45,), {}),
                    47: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 44), ("reasons", 46)]],
                        {},
                    ),
                    48: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "The testimonial text"},
                    ),
                    49: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Client name", "max_length": 100},
                    ),
                    50: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "e.g., 'Client since 2024' (optional)",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    51: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 48), ("author", 49), ("role", 50)]],
                        {},
                    ),
                    52: ("wagtail.blocks.DateBlock", (), {}),
                    53: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Short description"},
                    ),
                    54: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Link to full article (optional)",
                            "required": False,
                        },
                    ),
                    55: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "News",
                            "help_text": "'News' or 'Event'",
                            "max_length": 20,
                        },
                    ),
                    56: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 17),
                                ("date", 52),
                                ("summary", 53),
                                ("link", 54),
                                ("category", 55),
                            ]
                        ],
                        {},
                    ),
                    57: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Frequently Asked Questions", "max_length": 200},
                    ),
                    58: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 5,
                            "help_text": "Maximum number of FAQ items to display.",
                        },
                    ),
                    59: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 57), ("max_items", 58)]],
                        {},
                    ),
                    60: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    61: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Book Now", "max_length": 50},
                    ),
                    62: ("wagtail.blocks.URLBlock", (), {"default": "/booking/"}),
                    63: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 17),
                                ("text", 60),
                                ("button_text", 61),
                                ("button_link", 62),
                            ]
                        ],
                        {},
                    ),
                    64: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Book Your Screening", "max_length": 50},
                    ),
                    65: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Background image — a dark overlay will be added for readability.",
                            "required": False,
                        },
                    ),
                    66: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 17),
                                ("text", 60),
                                ("button_text", 64),
                                ("button_link", 62),
                                ("background_image", 65),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="tagline",
            field=models.TextField(
                blank=True,
                default="Providing accessible thermography services for residents of Vancouver Island and beyond…",
                help_text="Short description shown in the footer.",
            ),
        ),
    ]
