# Generated by Django 6.0.2 on 2026-02-18 03:09

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("announcement", 3),
                    ("hero", 9),
                    ("text_section", 10),
                    ("three_column_feature", 15),
                    ("text_with_image", 20),
                    ("two_column_info", 26),
                    ("services_grid", 30),
                    ("checklist", 36),
                    ("trust", 42),
                    ("why_choose_us", 45),
                    ("testimonial", 49),
                    ("news_item", 54),
                    ("faq_preview", 57),
                    ("call_to_action", 61),
                    ("big_cta", 64),
                    ("process_steps", 70),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Announcement text (supports links, bold, etc.)."
                        },
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("info", "Info — teal/brand"),
                                ("warning", "Warning — amber"),
                                ("success", "Success — green"),
                            ],
                            "help_text": "Colour scheme for the banner.",
                        },
                    ),
                    2: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Allow visitors to dismiss this banner?",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("message", 0), ("style", 1), ("dismissible", 2)]],
                        {},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Main heading (e.g., 'Welcome to Thermography')",
                            "max_length": 200,
                        },
                    ),
                    5: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Text below the heading", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Book an Appointment",
                            "help_text": "Text on the button",
                            "max_length": 50,
                        },
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "/booking/",
                            "help_text": "Where the button links to (e.g. /booking/ or https://example.com)",
                            "max_length": 200,
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Background image (optional)", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 4),
                                ("subheading", 5),
                                ("button_text", 6),
                                ("button_link", 7),
                                ("background_image", 8),
                            ]
                        ],
                        {},
                    ),
                    10: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "icon": "pilcrow",
                            "label": "Text Section",
                            "template": "home/blocks/richtext_block.html",
                        },
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional heading above the three columns.",
                            "max_length": 200,
                            "required": False,
                        },
                    ),
                    12: ("wagtail.blocks.CharBlock", (), {"max_length": 100}),
                    13: ("wagtail.blocks.TextBlock", (), {}),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 12), ("text", 13)]],
                        {},
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("section_heading", 11),
                                ("column_1", 14),
                                ("column_2", 14),
                                ("column_3", 14),
                            ]
                        ],
                        {},
                    ),
                    16: ("wagtail.blocks.CharBlock", (), {"max_length": 200}),
                    17: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Formatted text — supports bold, links, lists, etc."
                        },
                    ),
                    18: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "right",
                            "help_text": "'left' or 'right' — which side the image appears on",
                            "max_length": 5,
                        },
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 16),
                                ("text", 17),
                                ("image", 18),
                                ("image_position", 19),
                            ]
                        ],
                        {},
                    ),
                    21: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 200, "required": False},
                    ),
                    22: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Heading for the left column.",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    23: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Left column content."},
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Heading for the right column.",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    25: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Right column content."},
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 21),
                                ("left_heading", 22),
                                ("left_content", 23),
                                ("right_heading", 24),
                                ("right_content", 25),
                            ]
                        ],
                        {},
                    ),
                    27: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Our Services", "max_length": 200},
                    ),
                    28: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Optional text below the heading.",
                            "required": False,
                        },
                    ),
                    29: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "If checked, only services marked 'Featured' will display.",
                            "required": False,
                        },
                    ),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 27), ("subheading", 28), ("featured_only", 29)]],
                        {},
                    ),
                    31: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "What to Expect", "max_length": 200},
                    ),
                    32: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Optional intro text above the list.",
                            "required": False,
                        },
                    ),
                    33: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Checklist item text.", "max_length": 300},
                    ),
                    34: ("wagtail.blocks.StructBlock", [[("text", 33)]], {}),
                    35: ("wagtail.blocks.ListBlock", (34,), {}),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 31), ("intro", 32), ("items", 35)]],
                        {},
                    ),
                    37: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Trusted & Certified",
                            "max_length": 200,
                            "required": False,
                        },
                    ),
                    38: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Logo or badge image (optional).",
                            "required": False,
                        },
                    ),
                    39: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Label (e.g. 'IACT Certified').",
                            "max_length": 100,
                        },
                    ),
                    40: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 38), ("label", 39)]],
                        {},
                    ),
                    41: ("wagtail.blocks.ListBlock", (40,), {}),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 37), ("items", 41)]],
                        {},
                    ),
                    43: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Why Choose Us?", "max_length": 200},
                    ),
                    44: ("wagtail.blocks.ListBlock", (14,), {}),
                    45: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 43), ("reasons", 44)]],
                        {},
                    ),
                    46: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "The testimonial text"},
                    ),
                    47: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Client name", "max_length": 100},
                    ),
                    48: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "e.g., 'Client since 2024' (optional)",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    49: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 46), ("author", 47), ("role", 48)]],
                        {},
                    ),
                    50: ("wagtail.blocks.DateBlock", (), {}),
                    51: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Short description"},
                    ),
                    52: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Link to full article (optional)",
                            "required": False,
                        },
                    ),
                    53: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "News",
                            "help_text": "'News' or 'Event'",
                            "max_length": 20,
                        },
                    ),
                    54: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 16),
                                ("date", 50),
                                ("summary", 51),
                                ("link", 52),
                                ("category", 53),
                            ]
                        ],
                        {},
                    ),
                    55: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Frequently Asked Questions", "max_length": 200},
                    ),
                    56: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 5,
                            "help_text": "Maximum number of FAQ items to display.",
                        },
                    ),
                    57: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 55), ("max_items", 56)]],
                        {},
                    ),
                    58: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    59: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Book Now", "max_length": 50},
                    ),
                    60: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "/booking/",
                            "help_text": "e.g. /booking/ or https://example.com",
                            "max_length": 200,
                        },
                    ),
                    61: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 16),
                                ("text", 58),
                                ("button_text", 59),
                                ("button_link", 60),
                            ]
                        ],
                        {},
                    ),
                    62: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Book Your Screening", "max_length": 50},
                    ),
                    63: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Background image — a dark overlay will be added for readability.",
                            "required": False,
                        },
                    ),
                    64: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 16),
                                ("text", 58),
                                ("button_text", 62),
                                ("button_link", 60),
                                ("background_image", 63),
                            ]
                        ],
                        {},
                    ),
                    65: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "How It Works", "max_length": 200},
                    ),
                    66: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Step title (e.g. 'Book Online').",
                            "max_length": 100,
                        },
                    ),
                    67: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Short description of this step."},
                    ),
                    68: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 66), ("text", 67)]],
                        {},
                    ),
                    69: ("wagtail.blocks.ListBlock", (68,), {}),
                    70: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 65), ("steps", 69)]],
                        {},
                    ),
                },
            ),
        ),
    ]
