# Generated by Django 6.0.2 on 2026-02-21 21:01

import django.db.models.deletion
import modelsearch.index
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_alter_homepage_body"),
        ("services", "0004_remove_servicesindexpage_cancellation_policy"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quote",
                    models.TextField(
                        help_text="The testimonial text (1–3 sentences works best)."
                    ),
                ),
                (
                    "author_name",
                    models.CharField(
                        help_text="Client's name (or initials for privacy, e.g. 'Sarah M.').",
                        max_length=120,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        help_text="Optional context, e.g. 'Client since 2023' or 'Referred by Dr. Smith'.",
                        max_length=120,
                    ),
                ),
                (
                    "star_rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 star"),
                            (2, "2 stars"),
                            (3, "3 stars"),
                            (4, "4 stars"),
                            (5, "5 stars"),
                        ],
                        default=5,
                        help_text="Star rating (1–5).",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Featured testimonials appear on high-traffic pages (booking, first visit).",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional client photo (displayed as a small avatar).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to a specific service (optional). Shows relevant testimonials on service pages.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="testimonials",
                        to="services.servicepage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
                "ordering": ["sort_order", "-pk"],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
    ]
