# Generated by Django 6.0.2 on 2026-02-21 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_alter_homepage_body"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="logo",
            field=models.ForeignKey(
                blank=True,
                help_text="Business logo shown in the header. Upload a transparent PNG for best results.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="business_name",
            field=models.CharField(
                default="Thermography Clinic Vancouver Island",
                help_text="Business name shown in the header and footer.",
                max_length=100,
            ),
        ),
    ]
