# Generated by Django 6.0.2 on 2026-02-23 01:46

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0016_populate_homepage_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="deposit_policy",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Deposit/payment policy shown alongside the cancellation policy. Leave blank to hide.",
            ),
        ),
    ]
