# Generated by Django 6.0.2 on 2026-02-24 19:29

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_add_deposit_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="payment_methods",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Accepted payment methods (e.g. e-Transfer, credit card, cash). Shown on the booking page.",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("announcement", 3),
                    ("hero", 12),
                    ("text_section", 13),
                    ("three_column_feature", 18),
                    ("text_with_image", 23),
                    ("two_column_info", 29),
                    ("services_grid", 33),
                    ("checklist", 42),
                    ("trust", 48),
                    ("why_choose_us", 54),
                    ("testimonial", 58),
                    ("testimonials", 61),
                    ("news_item", 67),
                    ("faq_preview", 70),
                    ("call_to_action", 75),
                    ("big_cta", 79),
                    ("process_steps", 85),
                    ("upcoming_clinics", 87),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Announcement text (supports links, bold, etc.)."
                        },
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("info", "Info — teal/brand"),
                                ("warning", "Warning — amber"),
                                ("success", "Success — green"),
                            ],
                            "help_text": "Colour scheme for the banner.",
                        },
                    ),
                    2: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Allow visitors to dismiss this banner?",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("message", 0), ("style", 1), ("dismissible", 2)]],
                        {},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Main heading (e.g., 'Welcome to Thermography')",
                            "max_length": 200,
                        },
                    ),
                    5: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Text below the heading", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional small line below the subheading (e.g., 'Serving Vancouver Island since 2018')",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Book an Appointment",
                            "help_text": "Text on the button",
                            "max_length": 50,
                        },
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "/booking/",
                            "help_text": "Where the button links to (e.g. /booking/ or https://example.com)",
                            "max_length": 200,
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text for a second button (e.g., 'Learn About Thermography')",
                            "max_length": 50,
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "/resources/",
                            "help_text": "Where the second button links to (e.g. /resources/)",
                            "max_length": 200,
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Background image (optional)", "required": False},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 4),
                                ("subheading", 5),
                                ("supporting_line", 6),
                                ("button_text", 7),
                                ("button_link", 8),
                                ("secondary_button_text", 9),
                                ("secondary_button_link", 10),
                                ("background_image", 11),
                            ]
                        ],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "A free-form text area — type anything you want with bold, links, bullet points, etc.",
                            "icon": "pilcrow",
                            "label": "Text Section",
                            "template": "home/blocks/richtext_block.html",
                        },
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional heading above the three columns.",
                            "max_length": 200,
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Column heading (e.g. 'Non-Invasive').",
                            "max_length": 100,
                        },
                    ),
                    16: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Short description for this column."},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 15), ("text", 16)]],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("section_heading", 14),
                                ("column_1", 17),
                                ("column_2", 17),
                                ("column_3", 17),
                            ]
                        ],
                        {},
                    ),
                    19: ("wagtail.blocks.CharBlock", (), {"max_length": 200}),
                    20: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Formatted text — supports bold, links, lists, etc."
                        },
                    ),
                    21: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Photo for this section (optional). Without an image, text spans full width.",
                            "required": False,
                        },
                    ),
                    22: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("right", "Right")],
                            "help_text": "Which side the image appears on",
                        },
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 19),
                                ("text", 20),
                                ("image", 21),
                                ("image_position", 22),
                            ]
                        ],
                        {},
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 200, "required": False},
                    ),
                    25: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Heading for the left column.",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    26: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Left column content."},
                    ),
                    27: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Heading for the right column.",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    28: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Right column content."},
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 24),
                                ("left_heading", 25),
                                ("left_content", 26),
                                ("right_heading", 27),
                                ("right_content", 28),
                            ]
                        ],
                        {},
                    ),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Our Services", "max_length": 200},
                    ),
                    31: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Optional text below the heading.",
                            "required": False,
                        },
                    ),
                    32: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "If checked, only services marked 'Featured' will display.",
                            "required": False,
                        },
                    ),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 30), ("subheading", 31), ("featured_only", 32)]],
                        {},
                    ),
                    34: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "What to Expect", "max_length": 200},
                    ),
                    35: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Optional intro text above the list.",
                            "required": False,
                        },
                    ),
                    36: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Checklist item text.", "max_length": 300},
                    ),
                    37: ("wagtail.blocks.StructBlock", [[("text", 36)]], {}),
                    38: ("wagtail.blocks.ListBlock", (37,), {}),
                    39: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional button text (e.g. 'Learn More About Your First Visit').",
                            "max_length": 50,
                            "required": False,
                        },
                    ),
                    40: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Where the button links to (e.g. /your-first-visit/).",
                            "max_length": 200,
                            "required": False,
                        },
                    ),
                    41: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Optional image beside the checklist (e.g. calm clinic room).",
                            "required": False,
                        },
                    ),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 34),
                                ("intro", 35),
                                ("items", 38),
                                ("button_text", 39),
                                ("button_link", 40),
                                ("image", 41),
                            ]
                        ],
                        {},
                    ),
                    43: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Trusted & Certified",
                            "max_length": 200,
                            "required": False,
                        },
                    ),
                    44: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Logo or badge image (optional).",
                            "required": False,
                        },
                    ),
                    45: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Label (e.g. 'IACT Certified').",
                            "max_length": 100,
                        },
                    ),
                    46: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 44), ("label", 45)]],
                        {},
                    ),
                    47: ("wagtail.blocks.ListBlock", (46,), {}),
                    48: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 43), ("items", 47)]],
                        {},
                    ),
                    49: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Why Choose Us?", "max_length": 200},
                    ),
                    50: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Reason heading (e.g. 'Experienced Team').",
                            "max_length": 100,
                        },
                    ),
                    51: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Short description of this reason."},
                    ),
                    52: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 50), ("text", 51)]],
                        {},
                    ),
                    53: ("wagtail.blocks.ListBlock", (52,), {}),
                    54: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 49), ("reasons", 53)]],
                        {},
                    ),
                    55: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "The testimonial text"},
                    ),
                    56: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Client name", "max_length": 100},
                    ),
                    57: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "e.g., 'Client since 2024' (optional)",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    58: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 55), ("author", 56), ("role", 57)]],
                        {},
                    ),
                    59: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "What Our Clients Say",
                            "help_text": "Section heading.",
                            "max_length": 200,
                        },
                    ),
                    60: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 3,
                            "help_text": "How many testimonials to display (1–6).",
                            "max_value": 6,
                            "min_value": 1,
                        },
                    ),
                    61: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 59), ("show_count", 60)]],
                        {},
                    ),
                    62: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "News headline or event name.",
                            "max_length": 200,
                        },
                    ),
                    63: (
                        "wagtail.blocks.DateBlock",
                        (),
                        {"help_text": "Date of the news item or event."},
                    ),
                    64: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Short description (1-2 sentences)."},
                    ),
                    65: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Link to full article (optional)",
                            "required": False,
                        },
                    ),
                    66: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "News",
                            "help_text": "'News' or 'Event'",
                            "max_length": 20,
                        },
                    ),
                    67: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 62),
                                ("date", 63),
                                ("summary", 64),
                                ("link", 65),
                                ("category", 66),
                            ]
                        ],
                        {},
                    ),
                    68: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Frequently Asked Questions", "max_length": 200},
                    ),
                    69: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 5,
                            "help_text": "Maximum number of FAQ items to display.",
                        },
                    ),
                    70: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 68), ("max_items", 69)]],
                        {},
                    ),
                    71: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    72: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Button label (leave blank for no button).",
                            "max_length": 50,
                            "required": False,
                        },
                    ),
                    73: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Where the button links to (e.g. /booking/).",
                            "max_length": 200,
                            "required": False,
                        },
                    ),
                    74: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("bold", "Bold — coloured background"),
                                ("subtle", "Subtle — light background with border"),
                            ],
                            "help_text": "Visual weight of this section.",
                        },
                    ),
                    75: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 19),
                                ("text", 71),
                                ("button_text", 72),
                                ("button_link", 73),
                                ("style", 74),
                            ]
                        ],
                        {},
                    ),
                    76: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Book Your Screening", "max_length": 50},
                    ),
                    77: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "/booking/",
                            "help_text": "e.g. /booking/ or https://example.com",
                            "max_length": 200,
                        },
                    ),
                    78: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Background image — a dark overlay will be added for readability.",
                            "required": False,
                        },
                    ),
                    79: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 19),
                                ("text", 71),
                                ("button_text", 76),
                                ("button_link", 77),
                                ("background_image", 78),
                            ]
                        ],
                        {},
                    ),
                    80: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "How It Works", "max_length": 200},
                    ),
                    81: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Step title (e.g. 'Book Online', 'Visit Us', 'Get Results').",
                            "max_length": 100,
                        },
                    ),
                    82: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Short description of this step (1-2 sentences)."
                        },
                    ),
                    83: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 81), ("text", 82)]],
                        {},
                    ),
                    84: ("wagtail.blocks.ListBlock", (83,), {}),
                    85: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 80), ("steps", 84)]],
                        {},
                    ),
                    86: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Our Locations", "max_length": 200},
                    ),
                    87: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 86), ("subheading", 31)]],
                        {},
                    ),
                },
            ),
        ),
    ]
