# Generated by Django 6.0.2 on 2026-03-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0018_sitesettings_payment_methods_alter_homepage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="show_newsletter",
            field=models.BooleanField(
                default=True, verbose_name="Show newsletter signup"
            ),
        ),
    ]
