# Generated by Django 6.0.2 on 2026-03-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0019_homepage_show_newsletter"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="deposit_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=25.0,
                help_text="Non-refundable booking deposit amount ($). Displayed on the booking page and used as the default when creating deposit records.",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="etransfer_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="e-Transfer email address shown to clients for deposit payment. Leave blank to hide.",
                max_length=254,
            ),
        ),
    ]
