# Generated by Django 6.0.2 on 2026-03-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0020_sitesettings_deposit_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="etransfer_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="e-Transfer email address included in deposit confirmation emails sent to clients. Never displayed publicly on the website.",
                max_length=254,
            ),
        ),
    ]
