# Generated by Django 6.0.2 on 2026-03-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0021_alter_sitesettings_etransfer_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="email_deposit_cancelled",
            field=models.TextField(
                default="Hi {client_name},\n\nWe're writing to let you know that your thermography appointment{appointment_line}{service_line} has been cancelled.\n\nThe required ${amount} booking deposit was not received within 48 hours of booking, and the appointment has been automatically released.\n\nIf you'd like to rebook, you're welcome to visit our website and schedule a new appointment at any time.\n\nIf you believe this was an error or you've already sent payment, please reply to this email and we'll sort it out right away.\n\nBest regards,\nYour Thermography Team",
                help_text="Sent automatically when a deposit expires after 48 hours. Placeholders: {client_name}, {amount}, {appointment_line}, {service_line}.",
                verbose_name="Cancellation email body (48h rule)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="email_deposit_confirmation",
            field=models.TextField(
                default="Hi {client_name},\n\nThank you! We've received your ${amount} booking deposit and your appointment is confirmed.\n\n{details_line}Your deposit will be applied toward your service fee on the day of your visit.\n\nIf you need to reschedule or have any questions, please reply to this email.\n\nWe look forward to seeing you!\n\nBest regards,\nYour Thermography Team",
                help_text="Sent when the owner marks a deposit as received and clicks 'Send confirmation'. Placeholders: {client_name}, {amount}, {details_line} (appointment date + payment method or blank).",
                verbose_name="Deposit confirmation email body",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="email_deposit_request",
            field=models.TextField(
                default="Hi {client_name},\n\nThank you for booking your thermography appointment{appointment_line}!\n\nTo confirm your booking, a non-refundable ${amount} deposit is required.\n\nHOW TO PAY:\n  - e-Transfer: Send ${amount} to {etransfer_email}\n  - Cash: Pay at your appointment\n  - Cheque: Mail or bring in person\n\nPlease note: only send e-Transfers to the address above. We will never ask you to send money to a different address.\n\nYour deposit will be applied toward your service fee on the day of your visit.\n\nIf you have any questions, please reply to this email.\n\nBest regards,\nYour Thermography Team",
                help_text='Sent automatically when a client books. Available placeholders: {client_name}, {amount}, {appointment_line} (" on March 15, 2026" or blank), {etransfer_email}. Edit freely — placeholders are replaced when the email sends.',
                verbose_name="Deposit request email body",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="etransfer_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="e-Transfer email address included in deposit request emails sent to clients. Never displayed publicly on the website.",
                max_length=254,
            ),
        ),
    ]
