# Generated by Django 6.0.2 on 2026-03-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0023_alter_homepage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="show_policies",
            field=models.BooleanField(
                default=True,
                help_text="Pulls content from Settings → Site Settings → Policies.",
                verbose_name="Show payment & cancellation policies",
            ),
        ),
    ]
