# Generated by Django 6.0.2 on 2026-03-28 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0024_homepage_show_policies"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="email_deposit_confirmation",
        ),
    ]
