# Generated by Django 6.0.2 on 2026-10-03 10:47
#
# Refreshes the deposit request email so every environment uses the current
# wording AND includes a 72-hour deposit deadline notice (the deposit clock
# now starts the moment the booking is made).
#
# Two parts:
#   1. AlterField — updates the model-level default (fresh installs).
#   2. RunPython  — sets the stored SiteSettings value to the new wording.
#      This is an intentional one-time content update (migrations run once
#      per environment), so it also replaces any older customised wording in
#      production with the agreed copy. The owner can still edit it afterwards
#      in Wagtail admin → Settings → Site Settings → Email Templates.

from django.db import migrations, models


NEW_DEPOSIT_REQUEST = (
    "Hi {client_name},\n\n"
    "Thank you for booking your {service_name} appointment{appointment_line}!\n\n"
    "To confirm your booking, a non-refundable ${amount} e-transfer deposit is required.\n\n"
    "HOW TO PAY:\n"
    "  e-Transfer ${amount} to {etransfer_email}\n\n"
    "To secure your appointment, your deposit must be received within 72 hours of booking. "
    "If it is not received within 72 hours, your booking will be automatically cancelled.\n\n"
    "Your ${amount} deposit will be applied toward your {total_with_gst} appointment fee "
    "(includes GST). The remaining balance of {balance_due} is due on the day of your "
    "appointment and can be paid by e-transfer, cash, or cheque. "
    "You're also welcome to pay the full amount now.\n\n"
    "A receipt will be issued to you along with your report.\n\n"
    "Please note: only send e-Transfers to the address above. "
    "We will never ask you to send money to a different address.\n\n"
    "If you have any questions, please reply to this email.\n\n"
    "Best regards,\n"
    "Your Thermography Team"
)


def forwards(apps, schema_editor):
    """Set the deposit request email to the agreed wording on all rows."""
    SiteSettings = apps.get_model("home", "SiteSettings")
    for ss in SiteSettings.objects.all():
        if (ss.email_deposit_request or "") != NEW_DEPOSIT_REQUEST:
            ss.email_deposit_request = NEW_DEPOSIT_REQUEST
            ss.save(update_fields=["email_deposit_request"])


def backwards(apps, schema_editor):
    """No-op: the previous value may have been custom per-environment, so we
    don't attempt to restore it (avoids clobbering content on reverse)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0027_add_gst_rate_and_price_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="email_deposit_request",
            field=models.TextField(
                default=NEW_DEPOSIT_REQUEST,
                help_text=(
                    "Sent when a deposit request is approved. Available placeholders: "
                    "{client_name}, {amount}, {appointment_line}, {etransfer_email}, "
                    "{service_name}, {service_price} (price before tax), "
                    '{total_with_gst} (price + GST, e.g. "$325.50"), '
                    '{balance_due} (total minus deposit, e.g. "$300.50"). '
                    "Edit freely — placeholders are replaced when the email sends."
                ),
                verbose_name="Deposit request email body",
            ),
        ),
        migrations.RunPython(forwards, backwards),
    ]
