# Generated by Django 6.0.2 on 2026-02-16 19:42

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="TechnicianPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Technician's full name.", max_length=200
                    ),
                ),
                (
                    "bio",
                    wagtail.fields.RichTextField(
                        help_text="About the technician — background, passion, approach."
                    ),
                ),
                (
                    "credentials",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Certifications, training, qualifications (optional).",
                    ),
                ),
                (
                    "years_experience",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Years of experience (optional, shown as a stat).",
                        null=True,
                    ),
                ),
                (
                    "headshot",
                    models.ForeignKey(
                        blank=True,
                        help_text="Professional headshot / portrait photo.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Technician Page",
            },
            bases=("wagtailcore.page",),
        ),
    ]
