# Generated by Django 6.0.2 on 2026-02-17 19:43

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0001_initial"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="technicianpage",
            options={"verbose_name": "About Page"},
        ),
        migrations.AddField(
            model_name="technicianpage",
            name="clinic_description",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Tell visitors about the clinic — mission, values, what makes it special.",
            ),
        ),
        migrations.AddField(
            model_name="technicianpage",
            name="clinic_heading",
            field=models.CharField(
                default="About Our Clinic",
                help_text="Heading for the clinic section.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="technicianpage",
            name="clinic_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional photo of the clinic, office, or equipment.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
