# Generated by Django 6.0.2 on 2026-02-24 21:31

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0002_alter_technicianpage_options_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="technicianpage",
            name="thermographers_heading",
            field=models.CharField(
                blank=True,
                default="Meet Our Thermographers",
                help_text="Heading for the thermographers section. Leave blank to hide the section.",
                max_length=200,
            ),
        ),
        migrations.CreateModel(
            name="Thermographer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Thermographer's full name.", max_length=200
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        help_text="Job title or role, e.g. 'Certified Clinical Thermographer'.",
                        max_length=200,
                    ),
                ),
                (
                    "bio",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Short bio — background, qualifications, approach.",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thermographers",
                        to="about.technicianpage",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Professional headshot / portrait photo.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Thermographer",
                "verbose_name_plural": "Thermographers",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
