# Generated by Django 6.0.2 on 2026-02-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0003_technicianpage_thermographers_heading_thermographer"),
    ]

    operations = [
        migrations.AddField(
            model_name="technicianpage",
            name="subtitle",
            field=models.CharField(
                blank=True,
                help_text="Short subheading shown below the page title in the hero.",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="technicianpage",
            name="clinic_heading",
            field=models.CharField(
                blank=True,
                default="About Our Clinic",
                help_text="Optional heading above the clinic description. Leave blank if headings are in the description.",
                max_length=200,
            ),
        ),
    ]
