# Generated by Django 6.0.2 on 2026-02-24 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0004_technicianpage_subtitle_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="technicianpage",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional image shown beside the title and subtitle in the hero.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
