# Generated by Django 6.0.2 on 2026-03-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0005_technicianpage_hero_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="technicianpage",
            name="show_cta",
            field=models.BooleanField(
                default=True, verbose_name="Show 'Book an Appointment' section"
            ),
        ),
        migrations.AddField(
            model_name="technicianpage",
            name="show_newsletter",
            field=models.BooleanField(
                default=True, verbose_name="Show newsletter signup"
            ),
        ),
    ]
