# Generated by Django 6.0.2 on 2026-03-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0006_technicianpage_show_cta_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="technicianpage",
            name="show_policies",
            field=models.BooleanField(
                default=True, verbose_name="Show cancellation / deposit policies"
            ),
        ),
        migrations.AddField(
            model_name="technicianpage",
            name="show_testimonials",
            field=models.BooleanField(
                default=True, verbose_name="Show testimonials section"
            ),
        ),
    ]
