# Generated by Django 6.0.2 on 2026-03-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0008_technicianpage_cta_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="technicianpage",
            name="secondary_cta_button_text",
            field=models.CharField(
                default="View Services",
                help_text="Text shown on the secondary CTA button.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="technicianpage",
            name="secondary_cta_button_url",
            field=models.CharField(
                default="/services/",
                help_text="URL for the secondary CTA button.",
                max_length=300,
            ),
        ),
    ]
