# Generated by Django 6.0.2 on 2026-02-21 20:41

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="FirstVisitPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Optional intro text shown above the steps (e.g., 'We want you to feel comfortable and prepared…').",
                    ),
                ),
                (
                    "step1_heading",
                    models.CharField(
                        default="Book Your Appointment",
                        help_text="Heading for the booking step.",
                        max_length=200,
                    ),
                ),
                (
                    "step1_body",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Explain how to choose a clinic, date, and service.",
                    ),
                ),
                (
                    "step2_heading",
                    models.CharField(
                        default="Preparation Instructions",
                        help_text="Heading for the preparation step.",
                        max_length=200,
                    ),
                ),
                (
                    "step2_body",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="What the client needs to do before their appointment (e.g., avoid lotions, wear loose clothing).",
                    ),
                ),
                (
                    "step3_heading",
                    models.CharField(
                        default="Your Appointment",
                        help_text="Heading for the appointment step.",
                        max_length=200,
                    ),
                ),
                (
                    "step3_body",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="What happens during the thermography session.",
                    ),
                ),
                (
                    "step4_heading",
                    models.CharField(
                        default="Processing Your Results",
                        help_text="Heading for the waiting/processing step.",
                        max_length=200,
                    ),
                ),
                (
                    "step4_body",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="How long results take and what happens behind the scenes.",
                    ),
                ),
                (
                    "step5_heading",
                    models.CharField(
                        default="Your Report",
                        help_text="Heading for the sample report step.",
                        max_length=200,
                    ),
                ),
                (
                    "step5_body",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Describe what the report includes and show a sample if possible.",
                    ),
                ),
                (
                    "step6_heading",
                    models.CharField(
                        default="Follow-Up",
                        help_text="Heading for the follow-up step.",
                        max_length=200,
                    ),
                ),
                (
                    "step6_body",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Next steps — review with the technician, scheduling a follow-up, etc.",
                    ),
                ),
                (
                    "cta_text",
                    models.CharField(
                        default="Ready to book your first appointment?",
                        help_text="Call-to-action text shown at the bottom of the page.",
                        max_length=200,
                    ),
                ),
                (
                    "cta_button_text",
                    models.CharField(
                        default="Book Now",
                        help_text="Text on the CTA button.",
                        max_length=100,
                    ),
                ),
                (
                    "cta_button_url",
                    models.CharField(
                        default="/booking/",
                        help_text="URL the button links to (default: /booking/).",
                        max_length=300,
                    ),
                ),
                (
                    "step1_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional image for this step.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "step2_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional image for this step.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "step3_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional image for this step.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "step4_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional image for this step.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "step5_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional image (e.g., a redacted sample report).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "step6_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional image for this step.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Your First Visit Page",
            },
            bases=("wagtailcore.page",),
        ),
    ]
