# Generated by Django 6.0.2 on 2026-03-11 15:28

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_visit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="firstvisitpage",
            name="show_cta",
            field=models.BooleanField(
                default=True, verbose_name="Show bottom call-to-action"
            ),
        ),
        migrations.AddField(
            model_name="firstvisitpage",
            name="show_newsletter",
            field=models.BooleanField(
                default=True, verbose_name="Show newsletter signup"
            ),
        ),
        migrations.AddField(
            model_name="firstvisitpage",
            name="show_policies",
            field=models.BooleanField(
                default=True, verbose_name="Show cancellation / deposit policies"
            ),
        ),
        migrations.AddField(
            model_name="firstvisitpage",
            name="show_testimonials",
            field=models.BooleanField(
                default=True, verbose_name="Show testimonials section"
            ),
        ),
        migrations.AlterField(
            model_name="firstvisitpage",
            name="intro",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Optional intro text shown above the steps (e.g., 'We want you to feel comfortable and prepared...').",
            ),
        ),
        migrations.AlterField(
            model_name="firstvisitpage",
            name="step6_body",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Next steps -- review with the technician, scheduling a follow-up, etc.",
            ),
        ),
    ]
